cpu_temp_file: /sys/devices/virtual/thermal/thermal_zone0/temp
last_station: !!python/unicode 'lush'
server_address: 0.0.0.0
server_port: 10000
ssl_cert_file_location: certfile/server.pem
temp_sensor_file: /sys/bus/w1/devices/28-05168238f6ff/w1_slave
server_user_name: 'user'
server_user_password: 'pass'

default_city: Kyiv
owm_key: 'secret_key'
open_weather_api_link: 'api.openweathermap.org'

#temperarure read interval in second
read_interval: 60.0
audio_device_name: 'Lineout volume control'